nav:
  - ğŸ¡ ä¸»é¡µ: # ä¸»é¡µ/
      - index.md

  - java:
      - java/index.md
    
      - åŸºç¡€è¯­æ³•:
        - åº“å‡½æ•°: java/åŸºç¡€è¯­æ³•/åº“å‡½æ•°.md
        - å¹¶è¡Œ: java/åŸºç¡€è¯­æ³•/å¹¶è¡Œ.md
        - åå°„: java/åŸºç¡€è¯­æ³•/åå°„æœºåˆ¶.md
      - javaWeb:
        - Tomcat: java/javaWeb/Tomcat.md

      - Springbooot:
        - SpringbootåŸç†: java/Springboot/SpringbootåŸç†.md
        - é…ç½®ä¼˜å…ˆçº§: java/Springboot/é…ç½®ä¼˜å…ˆçº§.md
        - bean: java/Springboot/beanç®¡ç†.md
      - redis:
        - å•æœºé…ç½®é›†ç¾¤redis: java/redis/å•æœºé…ç½®é›†ç¾¤redis.md
        - NoSQL: java/redis/NoSQL.md
        - redisä»‹ç»: java/redis/redis.md
        - jedis: java/redis/jedis.md
        - SpringDataRedis: java/redis/SpringDataRedis.md
        - ç¼“å­˜: java/redis/ç¼“å­˜.md
        - ç¼“å­˜ä¸æ•°æ®åº“: java/redis/ç¼“å­˜ä¸æ•°æ®åº“.md
        - Redisson: java/redis/Redisson.md
        - åˆ†å¸ƒå¼é”: java/redis/åˆ†å¸ƒå¼é”.md
  
      - ElasticSearch:
        - ä»€ä¹ˆæ˜¯ES: java/ElasticSearch/introduce.md
        - å€’æ’ç´¢å¼•: java/ElasticSearch/å€’æ’ç´¢å¼•.md
        - ESåŸºç¡€çŸ¥è¯†: java/ElasticSearch/ESåŸºç¡€çŸ¥è¯†.md
        - æ‰“åˆ†æœºåˆ¶: java/ElasticSearch/æ‰“åˆ†æœºåˆ¶.md

      - æ¶ˆæ¯é˜Ÿåˆ—:
        - MQåŸºç¡€: java/æ¶ˆæ¯é˜Ÿåˆ—/MQåŸºç¡€.md
  - C++:
      - cpp/index.md
      - å¤è¯•æ³¨æ„ç‚¹-553: cpp/553.md
      - 553é€’å½’é—®é¢˜: cpp/553é€’å½’é—®é¢˜.md
      - cå­—ç¬¦æ•°ç»„å’Œcppå­—ç¬¦ä¸²ä¹‹é—´çš„è½¬æ¢: cpp/cå­—ç¬¦æ•°ç»„å’Œcppå­—ç¬¦ä¸²ä¹‹é—´çš„è½¬æ¢.md
      - è¯»å…¥é—®é¢˜: cpp/è¯»å…¥é—®é¢˜.md
      - C++åŸºç¡€çŸ¥è¯†:
        - stringstream: cpp/base/stringstream.md
        - ç±»:
            - é™æ€æ•°æ®æˆå‘˜: cpp/base/ç±»/é™æ€æ•°æ®æˆå‘˜.md
        - æ–‡ä»¶æ“ä½œ: 
          - å†™å…¥/è¯»å‡º: cpp/base/æ–‡ä»¶æ“ä½œ/æ–‡ä»¶æ“ä½œ.md
          - è°ƒæ•´æŒ‡é’ˆä½ç½®: cpp/base/æ–‡ä»¶æ“ä½œ/æŒ‡é’ˆä½ç½®è°ƒæ•´.md
        - æ¨¡æ¿:
          - æ•°ç»„ç±»æ¨¡æ¿: cpp/base/æ¨¡æ¿/æ•°ç»„ç±»æ¨¡æ¿.md
          - æ ˆç±»æ¨¡æ¿: cpp/base/æ¨¡æ¿/æ ˆç±»æ¨¡æ¿.md
          - é“¾è¡¨ç±»æ¨¡æ¿: cpp/base/æ¨¡æ¿/é“¾è¡¨ç±»æ¨¡æ¿.md
        - è¿ç®—ç¬¦é‡è½½:
          - åŠ å·è¿ç®—ç¬¦é‡è½½: cpp/base/è¿ç®—ç¬¦é‡è½½/åŠ å·è¿ç®—ç¬¦é‡è½½.md
          - å·¦ç§»è¿ç®—ç¬¦é‡è½½: cpp/base/è¿ç®—ç¬¦é‡è½½/å·¦ç§»è¿ç®—ç¬¦é‡è½½.md
          - è‡ªå¢è¿ç®—ç¬¦é‡è½½: cpp/base/è¿ç®—ç¬¦é‡è½½/è‡ªå¢è¿ç®—ç¬¦é‡è½½.md
          - èµ‹å€¼è¿ç®—ç¬¦é‡è½½: cpp/base/è¿ç®—ç¬¦é‡è½½/èµ‹å€¼è¿ç®—ç¬¦é‡è½½.md
          - å…³ç³»è¿ç®—ç¬¦é‡è½½: cpp/base/è¿ç®—ç¬¦é‡è½½/å…³ç³»è¿ç®—ç¬¦é‡è½½.md
          - å‡½æ•°è¿ç®—ç¬¦é‡è½½: cpp/base/è¿ç®—ç¬¦é‡è½½/å‡½æ•°è°ƒç”¨è¿ç®—ç¬¦é‡è½½.md
          - åŠ ç­‰è¿ç®—ç¬¦é‡è½½: cpp/base/è¿ç®—ç¬¦é‡è½½/åŠ ç­‰è¿ç®—ç¬¦é‡è½½.md
        - stlåº“å‡½æ•°: 
          - stl: cpp/base/stl/stl.md
          - stringå‡½æ•°è¯¦è§£: cpp/base/stl/string.md
        - æŒ‡é’ˆ:
          - å‡½æ•°æŒ‡é’ˆ: cpp/base/æŒ‡é’ˆ/å‡½æ•°æŒ‡é’ˆ.md
          - æ•°ç»„æŒ‡é’ˆ: cpp/base/æŒ‡é’ˆ/æ•°ç»„æŒ‡é’ˆ.md

      - å¸¸ç”¨api: 
        - æ•´å‹ä¸å­—ç¬¦ä¸²çš„è½¬æ¢: cpp/api/æ•´å‹ä¸å­—ç¬¦ä¸²çš„è½¬æ¢.md
        - éšæœºæ•°: cpp/api/rand.md
        - å¸¸ç”¨api: cpp/api/å¸¸ç”¨api.md
        - æ’åº: cpp/api/sort.md

      - cçŸ¥è¯†:
        - å­—ç¬¦ä¸²å‡½æ•°: cpp/c/å­—ç¬¦ä¸²å‡½æ•°.md
        - å†…å­˜ç§»åŠ¨é—®é¢˜: cpp/c/å†…å­˜.md

      - å†…å­˜åˆ†åŒºæ¨¡å‹:
        - åˆ†åŒºè¯¦æƒ…: cpp/å†…å­˜åˆ†åŒºæ¨¡å‹/åˆ†åŒºè¯¦æƒ….md
  - linux: 
    - wsl: 
      - wslé…ç½®ä»£ç†: linux/wsl/wslé…ç½®ä»£ç†.md
  - å‰ç«¯:
    - front_end/index.md
    - Vue3ç®€ä»‹: front_end/Vue3ç®€ä»‹.md
    - åˆ›å»ºVue3å·¥ç¨‹: front_end/åˆ›å»ºVue3å·¥ç¨‹.md
    - Vue3æ ¸å¿ƒè¯­æ³•: front_end/Vue3æ ¸å¿ƒè¯­æ³•.md
    - è·¯ç”±: front_end/è·¯ç”±.md
    - pinia : front_end/pinia.md
    - ç»„ä»¶é€šä¿¡: front_end/ç»„ä»¶é€šä¿¡.md
    - å…¶å®ƒ API: front_end/å…¶å®ƒ API.md
    - Vue3æ–°ç»„ä»¶: front_end/Vue3æ–°ç»„ä»¶.md





  - é¡¹ç›®:
    - project/index.md
    - åšé¡¹ç›®æµç¨‹: project/åšé¡¹ç›®æµç¨‹.md
    - RPC: 
      - ä»‹ç»: project/readme.md
    



  - æ ¸å¿ƒçŸ¥è¯†:
    - essential_knowledge/index.md
    - è®¡ç½‘:
      - tcpä¸udp: essential_knowledge/computer_network/tcpä¸udp.md
      - èº«ä»½è®¤è¯ä¸ä¼šè¯ç®¡ç†: essential_knowledge/computer_network/èº«ä»½è®¤è¯ä¸ä¼šè¯ç®¡ç†.md
      - HTTPåè®®: essential_knowledge/computer_network/http.md

  - é›¶ç¢çŸ¥è¯†:
      - fragmentKnowledge/index.md
      - å‘½åè§„èŒƒ:
        - è‹±æ–‡å•è¯è§„èŒƒ: fragmentKnowledge/å‘½åè§„èŒƒ/nameruler.md
        
  - ç®—æ³•:
      - algorithm/index.md
      - åŸºç¡€ç®—æ³•: 
        - å…¬å…±é¢ç§¯: algorithm/åŸºç¡€ç®—æ³•/å…¬å…±é¢ç§¯.md
        - kmp:  algorithm/åŸºç¡€ç®—æ³•/kmp.md
        - å•è°ƒæ ˆ: algorithm/åŸºç¡€ç®—æ³•/å•è°ƒæ ˆ.md
        - å‰ç¼€å’Œ: algorithm/åŸºç¡€ç®—æ³•/å‰ç¼€å’Œ.md
        - äºŒåˆ†: algorithm/åŸºç¡€ç®—æ³•/äºŒåˆ†.md
      - åŠ¨æ€è§„åˆ’:
        - æ•°ä½dp: algorithm/dp/æ•°ä½dp.md
      - å­—ç¬¦ä¸²:
        - å­—ç¬¦ä¸²å“ˆå¸Œ: algorithm/å­—ç¬¦ä¸²/å­—ç¬¦ä¸²å“ˆå¸Œ.md
      - æ•°å­¦:
        - gcd && lcm: algorithm/æ•°å­¦/gcd&lcm.md
      - ç»å…¸ç®—æ³•:
        - å›æ–‡ä¸²åˆ¤æ–­: algorithm/ç»å…¸ç®—æ³•/å›æ–‡ä¸²åˆ¤æ–­.md
        - åè½¬é“¾è¡¨: algorithm/ç»å…¸ç®—æ³•/ReverseLinkedList.md
        - ç®€å•æ’åºç®—æ³•: algorithm/ç»å…¸ç®—æ³•/ç®€å•æ’åºç®—æ³•.md
        - æ•°ç»„ä½ç½®äº¤æ¢: algorithm/ç»å…¸ç®—æ³•/æ•°ç»„äº¤æ¢ä½ç½®.md
      - äºŒå‰æ ‘:
        - äºŒå‰æœç´¢æ ‘:
          - å…³äºäºŒå‰æœç´¢æ ‘: algorithm/äºŒå‰æ ‘/äºŒå‰æœç´¢æ ‘/å…³äºäºŒå‰æœç´¢æ ‘.md
        - å‰åºä¸­åºæ„é€ æ ‘: algorithm/äºŒå‰æ ‘/å‰åº+ä¸­åºæ„é€ æ ‘.md
        - ååºä¸­åºæ„é€ æ ‘: algorithm/äºŒå‰æ ‘/ååº+ä¸­åºæ„é€ æ ‘.md
        - å‰åºååºæ„é€ æ ‘: algorithm/äºŒå‰æ ‘/å‰åº+ååºæ„é€ æ ‘.md
      - å›¾è®º: 
        - åŸºç¡€æ¨¡æ¿: algorithm/å›¾è®º/åŸºç¡€æ¨¡æ¿.md

  - åç«¯å…«è‚¡:
    - backendKnowledge/index.md
    - è®¡ç½‘:
      - httpè¯·æ±‚æ–¹æ³•: backendKnowledge/è®¡ç½‘/httpè¯·æ±‚æ–¹æ³•.md
  
  - git:
    - git/index.md
    - åˆ†æ”¯: git/branch.md


      
  - ç”Ÿæ´»:
    - life/index.md
    - ç…§ç‰‡:
        - è‹å·:
          - è‹å¤§:
              - æœ¬ç§‘æ¯•ä¸šç…§: life/ç…§ç‰‡/è‹å·/è‹å¤§/æœ¬ç§‘æ¯•ä¸šç…§.md
              - éšæ‰‹ä¸€æ‹: life/ç…§ç‰‡/è‹å·/è‹å¤§/éšæ‰‹ä¸€æ‹.md
      
            
    - æ—¥è®°:
      - 2024å¹´4æœˆ: life/æ—¥è®°/2024_4.md
      - 2024å¹´5æœˆ: life/æ—¥è®°/2024_5.md
    - å¨±ä¹:
      - æ¸¸æˆç‹md:
        - life/å¨±ä¹/æ¸¸æˆç‹md/index.md
        - åºŸäºŒ:
          - åºŸäºŒå±•å¼€: life/å¨±ä¹/æ¸¸æˆç‹md/åºŸäºŒ/åºŸäºŒå±•å¼€.md

    - ç”Ÿæ´»ä½œæ¯è§„åˆ’:
      - life/ç”Ÿæ´»ä½œæ¯è§„åˆ’/index.md
      - æ—¶é—´è¡¨: life/ç”Ÿæ´»ä½œæ¯è§„åˆ’/æ—¶é—´è¡¨.md


site_name: fmy's notes
site_url: https://fmy-fly.github.io/
repo_name: fmy-fly.github.io
repo_url: https://github.com/fmy-fly/fmy-fly.github.io/

theme:
  name: material
  logo: logo.ico
  favicon: logo.ico
  features:
    - navigation.tabs # ä¸€çº§å¯¼èˆªåœ¨æ¨ªç€çš„å¯¼èˆªæ 
    - content.code.annotate # å¯ä»¥åœ¨ä»£ç å—ä¸­å¢æ·»ç‚¹å‡»å±•ç¤ºçš„æ³¨é‡Šï¼Œå‚è§ https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    # - navigation.tracking # åœ°å€æ ä¸­çš„ URL ä¼šéšå½“å‰ä½ç½®å˜åŒ–ä¸ºå¯¹åº”å°èŠ‚çš„ URL
    - navigation.indexes # å°† index é¡µé¢ç›´æ¥é™„åˆ°å°èŠ‚åä¸Š
    - navigation.top # å›åˆ°é¡¶éƒ¨æŒ‰é’®
    # - navigation.sections # äºŒçº§å¯¼èˆªæ˜¯ç²—ä½“
    # - navigation.expand # å¯¼èˆªé»˜è®¤å±•å¼€
    - toc.follow # toc è·Ÿéš
    # - toc.integrate # æ–‡æ¡£ toc é›†æˆåˆ°æ€»ç›®å½•ä¸­
  language: "zh"
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Noto Serif SC # Roboto
    code: Roboto Mono
  custom_dir: overrides

edit_uri: ""

markdown_extensions:
  - toc:
      permalink: true # link for each title
      slugify: !!python/name:pymdownx.slugs.uslugify # enable Unicode link


  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - tables
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      # smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets: # å…è®¸å°†å…¶ä»–æ–‡ä»¶å†…å®¹æ’å…¥æ–‡ä»¶ï¼Œè¯­æ³•æ˜¯ --8<-- "filename.ext" ç­‰ï¼Œå‚è§ https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippets-notation
      auto_append:
        - includes/abbreviations.md
      base_path: ["docs"]
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  analytics:
    provider: google
    property: G-JT9BRCXKJJ
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/smd1121
  #   - icon: fontawesome/solid/envelope
  #     link: mailto:xianyuxuan@outlook.com

# extra:
#   search:
#     language: 'jp'
#   pagetime: 'on'

copyright: 'æœ¬é¡µé¢çš„å…¨éƒ¨å†…å®¹åœ¨ <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> å’Œ <a href="https://github.com/zTrix/sata-license">SATA</a> åè®®ä¹‹æ¡æ¬¾ä¸‹æä¾›ï¼Œé™„åŠ æ¡æ¬¾äº¦å¯èƒ½åº”ç”¨'

extra_css:
  - "from_oi_wiki/css/extra.css?v=13"
  - css/status.css
  - css/neoteroi-mkdocs.css

extra_javascript:
  - "from_oi_wiki/js/extra.js"
  - js/mathjax.js # æ”¯æŒæ•°å­¦å…¬å¼ï¼Œref : https://squidfunk.github.io/mkdocs-material/reference/mathjax
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js # æ”¯æŒè¡¨æ ¼æ’åº
  - js/tablesort.js

plugins:
  - search:
      separator: '[\s\u200b\-]'
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - statistics
  - termynal:
      title: ""
      buttons: macos
      prompt_literal_start:
        - "$"
        - ">"
        - "%"
